
const FIRE_SHOOT_VELOCITY = 14;
const FIRE_SPECIAL_SHOOT  = 14;
const PLAYER_LIVES = 100;
const PLAYER_BAR_WIDTH = PLAYER_LIVES;
const STARTING_NUMBER_ENEMIES = 5;
const STARTING_ENEMIES_VELOCITY = 1;
const VELOCITY_ENEMY_INCREASE = 1;
const UPDATE_DIFFICULTY = 50;
const NUMBER_OF_POWER_UPS = 3;
const ENEMY_DAMAGE = 10;

